# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 887f0466d56c0bb30877038b17c540ffd6981bf2cb850af2174778aac87c1c23cf728f18d33c87af7eecd3c70c1b0feaf8885c471e1d8b2b596d12cd172e02be

test:
  secret_key_base: 33fda2e69fc99f62d15c875fff4043437727e11c429d7c11e4ecd44e33aae6917966aa29b0aa1521e66ee3003e40395cc5eaab0215e84a7661384b1840904b5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
